# Generated by Django 5.0.9 on 2025-09-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a customer (not SAIA admin).', verbose_name='Customer User'),
        ),
    ]
