# Generated by Django 5.0.9 on 2024-10-15 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('type', models.CharField(default='none', max_length=100, verbose_name='Product Type')),
                ('quantity', models.FloatField(default=0, verbose_name='Quantity')),
                ('expiration', models.DateField(default=datetime.date.today, verbose_name='Expire Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('created_at',),
            },
        ),
    ]
