# Generated by Django 5.0.9 on 2025-09-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this product', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
