# Generated by Django 5.0.9 on 2025-09-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0002_add_company_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_categories', to='company.company')),
            ],
            options={
                'verbose_name': 'Knowledge Category',
                'verbose_name_plural': 'Knowledge Categories',
                'ordering': ['company', 'display_order', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Search Query')),
                ('results_count', models.PositiveIntegerField(verbose_name='Results Count')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='company.company')),
            ],
            options={
                'verbose_name': 'Knowledge Search Log',
                'verbose_name_plural': 'Knowledge Search Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('article_type', models.CharField(choices=[('service', 'Service Description'), ('policy', 'Policy/Terms'), ('faq', 'FAQ'), ('procedure', 'Procedure'), ('general', 'General Information')], default='general', max_length=20, verbose_name='Article Type')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for better search results', verbose_name='Keywords')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this article belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_articles', to='company.company')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='product.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'verbose_name_plural': 'Knowledge Articles',
                'ordering': ['company', 'category', 'display_order', 'title'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='product_kno_company_aea015_idx'), models.Index(fields=['company', 'article_type'], name='product_kno_company_2ac410_idx')],
            },
        ),
    ]
