# Generated by Django 5.0.9 on 2025-09-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0004_add_knowledge_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer_md', models.TextField(help_text='Answer in Markdown format for better formatting', verbose_name='Answer (Markdown)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization and search', verbose_name='Tags')),
                ('locale', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=5, verbose_name='Language')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('last_reviewed_at', models.DateTimeField(auto_now=True, help_text='When this FAQ was last reviewed for accuracy', verbose_name='Last Reviewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['company', 'display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='FAQAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrasing', models.TextField(help_text='Alternative way to ask the same question', verbose_name='Alternative Phrasing')),
            ],
            options={
                'verbose_name': 'FAQ Alias',
                'verbose_name_plural': 'FAQ Aliases',
            },
        ),
        migrations.AlterUniqueTogether(
            name='knowledgearticle',
            unique_together={('company', 'title')},
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='content_md',
            field=models.TextField(blank=True, help_text='Content in Markdown format for better formatting', verbose_name='Content (Markdown)'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='last_reviewed_at',
            field=models.DateTimeField(auto_now=True, help_text='When this content was last reviewed for accuracy', verbose_name='Last Reviewed'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='locale',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', help_text='Content language', max_length=5, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from title)', max_length=250, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Structured tags for better categorization', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='content',
            field=models.TextField(help_text='Plain text content - being migrated to Markdown', verbose_name='Content (Legacy)'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgearticle',
            unique_together={('company', 'slug'), ('company', 'title')},
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['company', 'locale', 'published'], name='product_kno_company_e32689_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['company', 'last_reviewed_at'], name='product_kno_company_43a5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['title'], name='product_kno_title_be5616_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['content'], name='product_kno_content_0f8942_idx'),
        ),
        migrations.AddField(
            model_name='faq',
            name='company',
            field=models.ForeignKey(help_text='Company this FAQ belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='company.company'),
        ),
        migrations.AddField(
            model_name='faqalias',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='product.faq'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['company', 'is_active', 'published'], name='product_faq_company_a9cc3d_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['company', 'locale'], name='product_faq_company_49a31b_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['question'], name='product_faq_questio_e7f44a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faq',
            unique_together={('company', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='faqalias',
            unique_together={('faq', 'phrasing')},
        ),
    ]
