# Generated by Django 5.0.9 on 2025-09-04 11:30

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Generate unique slugs for all knowledge articles"""
    KnowledgeArticle = apps.get_model('product', 'KnowledgeArticle')

    for article in KnowledgeArticle.objects.all():
        # Generate base slug from title
        base_slug = slugify(article.title)
        if not base_slug:
            base_slug = f"article-{article.id}"

        # Find unique slug within company
        slug = base_slug
        counter = 1

        while KnowledgeArticle.objects.filter(
            company=article.company,
            slug=slug
        ).exclude(pk=article.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        # Update the article with unique slug
        article.slug = slug
        article.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Reverse operation - clear all slugs"""
    KnowledgeArticle = apps.get_model('product', 'KnowledgeArticle')
    KnowledgeArticle.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_add_enhanced_fields'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
