# Generated by Django 5.0.9 on 2024-10-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Phone')),
                ('activity_name', models.CharField(max_length=255, verbose_name='Activity Name')),
                ('activity_type', models.CharField(choices=[('CR', 'Commercial'), ('SR', 'Service')], max_length=2, verbose_name='Activity Type')),
                ('activity_status', models.CharField(choices=[('1', 'Enabled'), ('0', 'Disabled')], default='1', max_length=1, verbose_name='Activity Status')),
                ('subscription_start_date', models.DateField(verbose_name='Subscription Start Date')),
                ('subscription_end_date', models.DateField(verbose_name='Subscription End Date')),
                ('subscription_status', models.CharField(choices=[('1', 'Enabled'), ('0', 'Disabled')], default='1', max_length=1, verbose_name='Subscription Status')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('status', models.CharField(choices=[('1', 'Enabled'), ('0', 'Disabled')], max_length=1, verbose_name='Branch Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company')),
            ],
        ),
    ]
