# Generated by Django 5.0.9 on 2025-09-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ai_instructions_template',
            field=models.TextField(blank=True, help_text="Custom AI instructions for this company's assistant. Leave blank to use default instructions.", null=True, verbose_name='AI Instructions Template'),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', help_text='Preferred language for AI assistant responses.', max_length=10, verbose_name='AI Language'),
        ),
        migrations.AddField(
            model_name='company',
            name='ai_temperature',
            field=models.FloatField(default=0.1, help_text='AI response creativity level (0.0 = very focused, 2.0 = very creative). Recommended: 0.1-0.3 for business use.', verbose_name='AI Creativity Level'),
        ),
        migrations.AddField(
            model_name='company',
            name='database_config_json',
            field=models.JSONField(blank=True, default=dict, help_text='Custom database connection settings for this company. Example: {"host": "db.company.com", "name": "company_db"}. Leave empty to use default connection.', verbose_name='Database Configuration'),
        ),
        migrations.AddField(
            model_name='company',
            name='enabled_tools_json',
            field=models.JSONField(blank=True, default=list, help_text='List of AI tools enabled for this company. Example: ["sales_analysis", "inventory_check"]. Leave empty to enable all tools.', verbose_name='Enabled AI Tools'),
        ),
    ]
