# Generated by Django 5.0.9 on 2025-09-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_add_ai_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='widget_is_active',
            field=models.BooleanField(default=True, help_text='Whether the website widget is active', verbose_name='Widget Active'),
        ),
        migrations.AddField(
            model_name='company',
            name='widget_position',
            field=models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left'), ('top-right', 'Top Right'), ('top-left', 'Top Left')], default='bottom-right', help_text='Widget position on the website', max_length=20, verbose_name='Widget Position'),
        ),
        migrations.AddField(
            model_name='company',
            name='widget_theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='Widget appearance settings (colors, fonts, etc.)', verbose_name='Widget Theme Configuration'),
        ),
        migrations.AddField(
            model_name='company',
            name='widget_welcome_message',
            field=models.TextField(blank=True, help_text='Welcome message shown to website visitors. Leave blank for default.', verbose_name='Widget Welcome Message'),
        ),
    ]
