# Generated by Django 5.0.9 on 2024-10-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Invoice No.')),
                ('price', models.FloatField(verbose_name='Invoice Price')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('print_date', models.DateField(blank=True, null=True, verbose_name='Print Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
                ('product_price', models.FloatField(verbose_name='Product price')),
                ('discount_percentage', models.FloatField(default=0.0, max_length=100, verbose_name='Discount percentage')),
                ('total_without_tax', models.FloatField(verbose_name='Total without tax')),
                ('tax_price', models.FloatField(verbose_name='Tax Price')),
                ('total_with_tax', models.FloatField(verbose_name='Total with tax')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Invoice Detail',
                'verbose_name_plural': 'Invoice Details',
            },
        ),
    ]
