# Generated by Django 5.0.9 on 2024-10-18 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2024, 10, 18), verbose_name='Transaction Date'),
        ),
    ]
